### ISSUE TITLE
Blum autoclicker problem

### ISSUE THREAD

**Issue by danielriosantos** [Asmar911/TELETAP#2]
Error when playing blum game:
Error occurred during start game: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://game-domain.blum.codes/api/v1/game/play')

![Screenshot 2024-10-14 183222](https://github.com/user-attachments/assets/5ce77d5a-07a0-4942-866b-d250d946b82d)

Thanks for the work!

**Comment by Asmar911** [comment]
this function will be stopped for now.
please download the new update
