### ISSUE TITLE
 No module named 'better_proxy'

### ISSUE THREAD

**Issue by thapld** [Asmar911/TELETAP#3]
![image](https://github.com/user-attachments/assets/f595ad5c-233e-4882-a60c-3edd94f086bb)

Python version: 3.11.4
Step by step:
1. START.bat
2. Add APP_ID & HASH
3. START.bat
4. Create session
5. Action 3, choose game blum

**Comment by PTPL-LKO** [comment]
> ![image](https://private-user-images.githubusercontent.com/38736191/377289595-f595ad5c-233e-4882-a60c-3edd94f086bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjM1ODcsIm5iZiI6MTcyOTE2MzI4NywicGF0aCI6Ii8zODczNjE5MS8zNzcyODk1OTUtZjU5NWFkNWMtMjMzZS00ODgyLWE2MGMtM2VkZDk0ZjA4NmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDExMDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwODU2NDNjODhjZThlYzcxODlhYjg2ODEyZDhiMTZiMjAzNmY0MmIxYzk4NzRiZDMzYWVjOGU0NTlmNTQ5MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BB6RhJPU0uOlQF53WOY77Hcwo-OoSf-NygPWizfP_R8)
> 
> Python version: 3.11.4 Step by step:
> 
> 1. START.bat
> 2. Add APP_ID & HASH
> 3. START.bat
> 4. Create session
> 5. Action 3, choose game blum

Yes, I'm also facing this issue even after re-installing better proxy

**Comment by RMOmd** [comment]
same problem.

**Comment by yanpaing007** [comment]
try better-proxy==1.1.5

**Comment by Asmar911** [comment]
For Termux use better-proxy=1.1.5
also Termux launcher will be updated soon (I'm working on new update)

**Comment by PTPL-LKO** [comment]
Not resolved yet

**Comment by PTPL-LKO** [comment]
> For Termux use better-proxy=1.1.5 also Termux launcher will be updated soon (I'm working on new update)

No
